version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5188:5188"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development # Altere para Production se não quiser o Swagger exposto
    volumes:
      - backend-data:/app
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx.docker.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    restart: always

volumes:
  backend-data:
